theme: jekyll-theme-cayman
title: N85UK UNRAID Applications
description: Production-ready Docker applications for UNRAID servers - X Webhook Receiver and AWS Ultimate Messaging. Actively maintained, multi-arch images on GHCR.
url: "https://apps.n85.uk"
baseurl: ""
show_downloads: false

# SEO Configuration
lang: en-GB
author: N85UK
twitter:
  username: N85UK
logo: /assets/logo.png
social:
  name: N85UK
  links:
    - https://github.com/N85UK

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

# Exclude from build
exclude:
  - README.md
  - WEBSITE_IMPROVEMENTS.md
  - .github/
  - reports/
